name: Auto Assign
on:
  push:
    branches: [master]
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .github/auto-assign.yml
