
name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Curl
        run: |
          echo curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
                    -H "Authorization: Bearer HBmtn0pqqo4t-yxITCKRIASOOev3cJvmtC-pn1ap" \
                    -H "Content-Type:application/json"
    # Proof HTML                
      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./
